module.exports = {
    ptbr: {
        error: {
            missingUser: `Por favor, lembre-se de inserir o usuário que deseja punir`,
            selfWarn: `Você não pode dar warn para si próprio`,
            highRole: `Você não pode dar warn neste usuário porque o cargo é **igual ou superior** ao seu`,
            proofSize: `Parece que o seu anexo não é suportado por mim devido ao tamanho, e, portanto, não será incluído no warn`,
            unavailable: `Indisponível`,
            missingPerms: `Você não possui permissão`,
            ownerPunishment: `Não é possível fazer punições no(a) Dono(a)`,
            botPunishment: `Não posso dar warns em Bots`,
        },
        noReason: `Sem motivo`,
        warning: `Você está dando warn em {user}, por favor, verifique as informações e clique no botão`,
        details: `Detalhes`,
        user: `Usuário`,
        reason: `Motivo`,
        attachment: `Anexos`,
        buttons: {
            confirm: `Confirmar Ação`,
            cancel: `Cancelar Essa Punição`
        },
        warned: `O warn foi registrado com sucesso`,
        canceled: `O warn foi cancelado, o usuário não teve sua punição registrada`,
        accessAttachment: `Acessar Anexo`,
        missingPerms: `Você não possui permissão`,
        ownerPunishment: `Não é possível fazer punições no(a) Dono(a)`,
        botPunishment: `Não posso dar warns em Bots`,
    },
    enus: {
        error: {
            missingUser: `Please remember to enter the user you want to punish`,
            selfWarn: `You cannot warn yourself`,
            highRole: `You cannot warn this user because the role is **equal or higher** than yours`,
            proofSize: `It seems that your attachment is not supported by me due to size, and therefore, it will not be included in the warning`,
            unavailable: `Unavailable`,
            missingPerms: `You do not have permission`,
            ownerPunishment: `Cannot perform punishments on the Owner`,
            botPunishment: `Cannot warn Bots`,
        },
        noReason: `No reason`,
        warning: `You are warning {user}, please check the information and click the button`,
        details: `Details`,
        user: `User`,
        reason: `Reason`,
        attachment: `Attachments`,
        buttons: {
            confirm: `Confirm Action`,
            cancel: `Cancel This Punishment`
        },
        warned: `The warning has been successfully registered`,
        canceled: `The warning has been canceled, the user did not have their punishment recorded`,
        accessAttachment: `Access Attachment`,
        missingPerms: `You do not have permission`,
        ownerPunishment: `Cannot perform punishments on the Owner`,
        botPunishment: `Cannot warn Bots`,
    },
    eses: {
        error: {
            missingUser: `Por favor, recuerda ingresar el usuario que deseas castigar.`,
            selfWarn: `No puedes advertirte a ti mismo`,
            highRole: `No puedes advertir a este usuario porque el cargo es **igual o superior** al tuyo`,
            proofSize: `Parece que tu adjunto no es compatible conmigo debido al tamaño y, por lo tanto, no se incluirá en la advertencia`,
            unavailable: `No disponible`,
            missingPerms: `No tienes permisos`,
            ownerPunishment: `No se pueden realizar castigos en el Dueño/a`,
            botPunishment: `No puedo advertir a los Bots`,
        },
        noReason: `Sin motivo`,
        warning: `Estás advirtiendo a {user}, por favor, verifica la información y haz clic en el botón`,
        details: `Detalles`,
        user: `Usuario`,
        reason: `Motivo`,
        attachment: `Adjuntos`,
        buttons: {
            confirm: `Confirmar Acción`,
            cancel: `Cancelar Esta Sanción`
        },
        warned: `La advertencia se ha registrado con éxito`,
        canceled: `La advertencia ha sido cancelada, el usuario no tuvo su castigo registrado`,
        accessAttachment: `Acceder al Adjunto`,
        missingPerms: `No tienes permisos`,
        ownerPunishment: `No se pueden realizar castigos en el Dueño/a`,
        botPunishment: `No puedo advertir a los Bots`,
    }
};
